version: "3"
services:
  gitbook_wiki:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_gitbook
    hostname: gitbook
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./book:/book
      - ./start.sh:/start.sh
    environment:
      BOOK_URL: https://github.com/iansmith123/gitbook-docker
      LISTEN_API: some_uri
      API_PORT: 35698
    command: ['/start.sh']

