version: "3"
services:
  node_gitlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_gitbook
#    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./book:/book
    command: ['gitbook', 'serve']

